import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";
import TanstackProvider from "@/providers/TanstackProvider";
import { Toaster } from "react-hot-toast";
import "@/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "TukuKlik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="scroll-smooth antialiased" lang="en">
      <body className={`${fontSans.className} m-0 p-0`}>
        <TanstackProvider>
          <AuthProvider>
            <Toaster />
            {children}
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
