import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/header/Header";
import "@/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "TukuKlik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="scroll-smooth antialiased" lang="en">
      <body className={`${fontSans.className} m-0 p-0`}>
        <div className="relative flex min-h-screen flex-col">
          <Header />
          <main className="bg-gray-100 pb-3">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
